CREATE TABLE "users" (
  "username" varchar PRIMARY KEY,
  "hashed_password" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password_changed_at" timestamptz NOT NULL DEFAULT '0001-01-01 00:00:00Z',
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "accounts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_name" varchar NOT NULL,
  "balance" bigint NOT NULL,
  "account_owner" varchar NOT NULL,
  "account_type" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "budgets" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "budget_name" varchar NOT NULL,
  "amount" bigint NOT NULL,
  "budget_owner" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "transactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" varchar NOT NULL,
  "amount" bigint NOT NULL,
  "account_id" int NOT NULL,
  "budget_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE UNIQUE INDEX ON "budgets" ("budget_name", "budget_owner");

CREATE INDEX ON "transactions" ("account_id", "budget_id");

ALTER TABLE "accounts" ADD FOREIGN KEY ("account_owner") REFERENCES "users" ("username");

ALTER TABLE "budgets" ADD FOREIGN KEY ("budget_owner") REFERENCES "users" ("username");

ALTER TABLE "transactions" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("budget_id") REFERENCES "budgets" ("id");