// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"time"
)

type Account struct {
	ID           int32
	AccountName  string
	Balance      int64
	AccountOwner string
	AccountType  string
	CreatedAt    time.Time
}

type Budget struct {
	ID          int32
	BudgetName  string
	Amount      int64
	BudgetOwner string
	CreatedAt   time.Time
}

type Transaction struct {
	ID          int32
	Description string
	Amount      int64
	AccountID   int32
	BudgetID    int32
	CreatedAt   time.Time
}

type User struct {
	Username          string
	HashedPassword    string
	Email             string
	PasswordChangedAt time.Time
	CreatedAt         time.Time
}
