// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int32) error
	DeleteAllUserAccounts(ctx context.Context, accountOwner string) error
	DeleteBudget(ctx context.Context, id int32) error
	DeleteTransaction(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, username string) error
	GetAccount(ctx context.Context, id int32) (Account, error)
	GetBudget(ctx context.Context, id int32) (Budget, error)
	GetTransaction(ctx context.Context, id int32) (Transaction, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListBudgets(ctx context.Context, arg ListBudgetsParams) ([]Budget, error)
	ListTransactionsByAccount(ctx context.Context, arg ListTransactionsByAccountParams) ([]Transaction, error)
	ListTransactionsByBudget(ctx context.Context, arg ListTransactionsByBudgetParams) ([]Transaction, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
